name: van_tan_export
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
homepage: ''

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flame: 1.25.0
  path: 1.9.0
  provider: 6.0.2
  sqflite: 2.4.0
  google_fonts: 5.0.0
  video_player: 2.9.3
  flutter_soloud: 3.1.8
  shared_preferences: 2.0.13

  core_200_d020:
    path: ../../core/core_200_d020
  core_200_d040:
    path: ../../core/core_200_d040
  core_200_d060:
    path: ../../core/core_200_d060
  core_200_d080:
    path: ../../core/core_200_d080

  screen_200_d020:
    path: ../../screens/screen_200_d020

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
